# @file ci-tests.yml
---
name: klp-build tests

on:
  pull_request:
    branches:
      - 'devel'
      - 'main'
  push:
    branches:
      - '*'
      - '!devel'
      - '!main'

jobs:
  distribution-check:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest
      options: --device /dev/fuse --cap-add SYS_ADMIN --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        zypper --gpg-auto-import-keys addrepo https://download.opensuse.org/repositories/home:/fgonzalez/openSUSE_Tumbleweed/home:fgonzalez.repo
        zypper --gpg-auto-import-keys refresh
        zypper --non-interactive install --no-confirm git-fs python3-devel git python3-pytest tox python3-magic

    - name: git-fs test
      run: |
        git clone https://github.com/fgyanz/git-fs
        cd git-fs
        id
        git fs -V
        git fs -m -f
